### ISSUE TITLE
distributionFormatVersion: necessary?

### ISSUE THREAD

**Issue by hugoledoux** [cityjson/metadata-extended#2]
it's the version of the CityJSON file, so why store it since it's a direct access?

**Comment by liberostelios** [comment]
I guess this can be considered useful for someone that wants to parse the metadata for data discovery, without having to dig into the details of CityJSON.

**Comment by hugoledoux** [comment]
hmmm, but they will have to look into the details of cityjson anyway to be able to fetch the metadata in the first place, since we do not store them with a known format, but our own schema.

**Comment by hugoledoux** [comment]
but let's assume a user wants to use the ISO19115 properties and expects them, shouldn't then we be complete and add the `distributionFormat` and state this is a CityJSON file?
