### ISSUE TITLE
`fileIdentifier`: this is the name of the file?

### ISSUE THREAD

**Issue by hugoledoux** [cityjson/metadata-extended#4]
if yes, should it be stored? That sounds counter-intuitive to me, no?

**Comment by liberostelios** [comment]
Same as #2, I think this is more about data discovery and immediately extracting information about the dataset. Since the ISO proposes it and the same question applies to all datasets, I suppose they have a reason for wanting this to be in there. But I am not an expert to express an opinion.

**Comment by hugoledoux** [comment]
okay let's leave it in the metadata
